name: "Lint Commit Message"
on:
  push:
    branches:
      - main
jobs:
  lint-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Check for issue ID"
        run: |
          if ! git log -1 --pretty=%B | grep -qE "#[0-9]+"; then
            echo "Commit message must contain an issue ID (e.g., #123)"
            exit 1
          fi
