name: Process Adherence

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check_process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for correct labels and status transitions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 scripts/check_status_transitions.py
